# Generated by Django 3.0.3 on 2020-03-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField(max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
